const LOCAL_SOURCE = ["local-proa-fjd"];
const AMR_SOURCES = ["local-proa-fjd", "idsa-amr-2024"];

export const SECTIONS = Object.freeze([
  { id: "atlas", label: "Atlas bacteriano", icon: "🧫" },
  { id: "antibiotics", label: "Pokédex antibióticos", icon: "💊" },
  { id: "mechanisms", label: "Mecanismos MDR", icon: "🧬" },
  { id: "matrix", label: "Heatmap cobertura", icon: "▦" },
  { id: "wizard", label: "Selector clínico", icon: "🎯" },
  { id: "cases", label: "Trampas de guardia", icon: "⚠️" },
  { id: "deep", label: "Lectura escondida", icon: "📚" },
]);

const organismData = [
  {
    id: "saureus",
    dex: "G+001",
    group: "positive",
    name: "Staphylococcus aureus",
    short: "S. aureus",
    icon: "🟣",
    type: "coco en racimos",
    tags: ["SASM", "SARM"],
    syndromes: "IPPB, abscesos, bacteriemia, endocarditis, neumonía, osteomielitis.",
    cover:
      "SASM: cloxacilina/cefazolina. SARM: vancomicina, daptomicina según foco, linezolid en neumonía, ceftarolina si dirigida; ceftobiprol solo si ficha/protocolo lo justifica.",
    gap: "SARM no queda cubierto por beta-lactámicos habituales. Daptomicina no neumonía.",
    trap:
      "Si el objetivo principal es SASM, no uses pip-tazo o ceftriaxona como “suficiente” si puedes usar cloxacilina/cefazolina.",
    search:
      "staphylococcus aureus s aureus sasm sarm mrsa mssa cloxacilina cefazolina ceftarolina ceftobiprol daptomicina vancomicina",
  },
  {
    id: "spyogenes",
    dex: "G+002",
    group: "positive",
    name: "Streptococcus pyogenes",
    short: "S. pyogenes",
    icon: "🟣",
    type: "coco en cadenas",
    tags: ["Sensible", "Toxina"],
    syndromes: "Faringoamigdalitis, erisipela/celulitis, fascitis necrotizante, shock tóxico.",
    cover: "Penicilina o amoxicilina. En cuadro toxinogénico, añadir clindamicina según protocolo.",
    gap: "El antibiótico no sustituye cirugía si hay necrosis.",
    trap: "En fascitis necrotizante, pensar en control quirúrgico y antitoxina; no solo “cubre Strep”.",
    search: "streptococcus pyogenes grupo a penicilina amoxicilina clindamicina fascitis",
  },
  {
    id: "spneumo",
    dex: "G+003",
    group: "positive",
    name: "Streptococcus pneumoniae",
    short: "Neumococo",
    icon: "🟣",
    type: "diplococo",
    tags: ["NAC", "SNC"],
    syndromes: "NAC, otitis, sinusitis, meningitis, bacteriemia.",
    cover: "Amoxicilina en respiratorio no grave; ceftriaxona/cefotaxima en hospital o meningitis según CMI.",
    gap: "El punto de corte cambia según foco: meningitis exige margen mucho más estricto.",
    trap: "No extrapoles sensibilidad respiratoria a meningitis.",
    search: "neumococo streptococcus pneumoniae meningitis nac ceftriaxona amoxicilina",
  },
  {
    id: "enterococcus",
    dex: "G+004",
    group: "positive",
    name: "Enterococcus faecalis sensible / E. faecium-VRE",
    short: "Enterococcus",
    icon: "🟣",
    type: "coco",
    tags: ["LAME", "VRE"],
    syndromes: "ITU, bacteriemia, endocarditis, intraabdominal nosocomial.",
    cover:
      "E. faecalis sensible: ampicilina/amoxicilina o penicilina G dirigida. E. faecium/VRE: tratamiento dirigido con AST y PROA.",
    gap:
      "Cefalosporinas no cubren Enterococcus como cobertura propia. E. faecium suele ser resistente a ampicilina y puede ser VRE.",
    trap:
      "Ceftriaxona + ampicilina es sinergia en endocarditis por E. faecalis; ceftriaxona sola no cubre Enterococcus.",
    search: "enterococcus faecalis sensible faecium ampicilina cefalosporinas vre endocarditis ceftriaxona sinergia",
  },
  {
    id: "listeria",
    dex: "G+005",
    group: "positive",
    name: "Listeria monocytogenes",
    short: "Listeria",
    icon: "🟣",
    type: "bacilo",
    tags: ["SNC", "LAME"],
    syndromes: "Meningitis/meningoencefalitis en anciano, embarazo, neonato o inmunodeprimido; bacteriemia.",
    cover:
      "En SNC: ampicilina IV o amoxicilina IV según protocolo. Penicilina G dirigida si sensibilidad y foco encajan.",
    gap: "Cefalosporinas no cubren Listeria. No leer amoxicilina oral como pauta de meningitis.",
    trap: "Anciano con meningitis + ceftriaxona sola = hueco crítico.",
    search: "listeria meningitis anciano embarazo ampicilina iv amoxicilina iv ceftriaxona",
  },
  {
    id: "clostridium",
    dex: "A001",
    group: "anaerobe",
    name: "Clostridium / Clostridioides",
    short: "Clostridium",
    icon: "🟤",
    type: "anaerobio Gram +",
    tags: ["Anaerobio", "CDI"],
    syndromes: "C. difficile, mionecrosis, infecciones polimicrobianas profundas.",
    cover: "Depende del síndrome. Polimicrobiana: pip-tazo/carbapenémico o beta-lactámico + metronidazol.",
    gap: "Aztreonam y aminoglucósidos no cubren anaerobios.",
    trap: "Vancomicina IV no trata CDI luminal; fidaxomicina/vancomicina oral actúan en colon.",
    search: "clostridium clostridioides difficile metronidazol fidaxomicina vancomicina oral anaerobios",
  },
  {
    id: "neisseria",
    dex: "G-001",
    group: "negative",
    name: "Neisseria meningitidis / gonorrhoeae",
    short: "Neisseria",
    icon: "🔵",
    type: "diplococo GN",
    tags: ["ITS", "SNC"],
    syndromes: "Meningitis/meningococemia; uretritis/cervicitis, EIP y artritis gonocócica.",
    cover:
      "Gonococo: ceftriaxona es referencia; cefixima solo si ceftriaxona no está disponible/no es factible. Meningitis: ajustar a protocolo.",
    gap: "Resistencia adquirida en gonococo obliga a guía actualizada; faringe es más difícil de erradicar.",
    trap: "Gonococo faríngeo requiere test de curación; si fallo, cultivo/AST y experto.",
    search: "neisseria meningitidis gonorrhoeae ceftriaxona cefixima faringea test curacion meningitis gonococo",
    sourceIds: ["local-proa-fjd", "cdc-gonorrhea-2021"],
  },
  {
    id: "haemo-morax",
    dex: "G-002",
    group: "negative",
    name: "Haemophilus influenzae / Moraxella",
    short: "H. influenzae/Moraxella",
    icon: "🔵",
    type: "cocobacilos",
    tags: ["Respiratorio", "β-lactamasa"],
    syndromes: "EPOC reagudizado, otitis, sinusitis, NAC seleccionada.",
    cover: "Amox-clav, cefuroxima o ceftriaxona según gravedad y foco.",
    gap: "Frecuente producción de beta-lactamasa: amoxicilina sola puede fallar.",
    trap: "Si fracaso a amoxicilina en EPOC/ORL, piensa en beta-lactamasa.",
    search: "haemophilus influenzae moraxella epoc amoxicilina clavulanico cefuroxima",
  },
  {
    id: "ecoli-kleb-prot",
    dex: "G-003",
    group: "negative",
    name: "E. coli / Klebsiella / Proteus",
    short: "Enterobacterales comunes",
    icon: "🔵",
    type: "bacilos GN",
    tags: ["ITU", "Abdomen"],
    syndromes: "ITU, pielonefritis, bacteriemia, intraabdominal, colangitis, prostatitis.",
    cover: "Ceftriaxona si no BLEE ni AmpC de alto riesgo y foco adecuado. Carbapenémico si BLEE grave/invasiva.",
    gap: "Klebsiella es resistente a ampicilina/amoxicilina. Proteus no es Pseudomonas.",
    trap: "No escales a antipseudomónico solo porque el cultivo dice “Proteus”.",
    search: "escherichia coli klebsiella proteus enterobacterales ceftriaxona no blee no ampc itu pielonefritis",
  },
  {
    id: "ampc-trio",
    dex: "G-004",
    group: "negative",
    name: "Enterobacter cloacae / K. aerogenes / C. freundii",
    short: "AmpC alto riesgo",
    icon: "🔵",
    type: "Enterobacterales AmpC",
    tags: ["AmpC", "Trampa"],
    syndromes: "Bacteriemia, ITU complicada, nosocomial, intraabdominal, dispositivos.",
    cover: "Cefepime si sensible y CMI favorable. Carbapenémico si grave/profunda, BLEE coproducida o CMI problemática.",
    gap: "Evitar ceftriaxona/cefotaxima en infección invasiva aunque parezca sensible.",
    trap: "La sensibilidad inicial a ceftriaxona puede inducir resistencia durante tratamiento.",
    search: "enterobacter cloacae klebsiella aerogenes citrobacter freundii ampc cefepime ceftriaxona",
    sourceIds: AMR_SOURCES,
  },
  {
    id: "pseudomonas",
    dex: "NF001",
    group: "negative",
    name: "Pseudomonas aeruginosa",
    short: "Pseudomonas",
    icon: "🟢",
    type: "no fermentador",
    tags: ["Pseudomonas", "DTR"],
    syndromes: "Nosocomial, bronquiectasias/FQ, neutropenia, UCI, ITU sondada, quemaduras, ectima gangrenoso.",
    cover:
      "Pip-tazo, ceftazidima, cefepime, aztreonam si sensible; meropenem/imipenem si indicación. DTR: nuevos BL/BLI o cefiderocol según AST.",
    gap: "No la cubren ceftriaxona, cefuroxima, amox-clav ni ertapenem.",
    trap: "Ertapenem no cubre Pseudomonas: APE.",
    search: "pseudomonas aeruginosa cefepime ceftazidima piperacilina tazobactam ertapenem dtr",
    sourceIds: AMR_SOURCES,
  },
  {
    id: "acinetobacter",
    dex: "NF002",
    group: "negative",
    name: "Acinetobacter baumannii / CRAB",
    short: "CRAB",
    icon: "🟢",
    type: "cocobacilo/no fermentador",
    tags: ["UCI", "CRAB"],
    syndromes: "UCI, neumonía asociada a ventilación, heridas, bacteriemia, brotes.",
    cover:
      "Si infección real: sulbactam-durlobactam + meropenem/imipenem si disponible; si no, alta dosis de ampicilina-sulbactam + otro agente.",
    gap: "No asumir que meropenem amplio cubre CRAB.",
    trap: "Vía aérea con CRAB puede ser colonización: confirma síndrome infeccioso antes de combinar.",
    search: "acinetobacter baumannii crab sulbactam durlobactam colistina cefiderocol uci",
    sourceIds: AMR_SOURCES,
  },
  {
    id: "steno",
    dex: "NF003",
    group: "negative",
    name: "Stenotrophomonas maltophilia",
    short: "Stenotrophomonas",
    icon: "🟢",
    type: "no fermentador",
    tags: ["Colonización", "L1/L2"],
    syndromes:
      "Colonización respiratoria frecuente; infección real en críticos, inmunodeprimidos, catéter o neumonía compatible.",
    cover:
      "Solo si infección real + AST + PROA. Si moderada-grave: dos agentes entre cefiderocol, minociclina, TMP-SMX o levofloxacino; alternativa CAZ-AVI + aztreonam.",
    gap: "Carbapenémicos inútiles por L1; muchas cefalosporinas fallan por L2.",
    trap: "Primero distinguir infección de colonización. No usar ceftazidima como tratamiento.",
    search: "stenotrophomonas maltophilia infeccion real ast proa tmp smx minociclina levofloxacino cefiderocol ceftazidima",
    sourceIds: AMR_SOURCES,
  },
  {
    id: "bacteroides",
    dex: "A002",
    group: "anaerobe",
    name: "Bacteroides fragilis y anaerobios GN",
    short: "Bacteroides/anaerobios",
    icon: "🟤",
    type: "anaerobio GN",
    tags: ["Abdomen", "Metronidazol"],
    syndromes: "Intraabdominal, abscesos, pelvis, pie diabético, mordeduras mixtas.",
    cover:
      "Pip-tazo, carbapenémicos, amox-clav en cuadros comunitarios seleccionados, o metronidazol asociado a cefalosporina.",
    gap: "Ceftriaxona, cefepime y ceftazidima solas no bastan. Aztreonam no cubre anaerobios.",
    trap: "Ceftriaxona para abdomen suele necesitar metronidazol.",
    search: "bacteroides fragilis anaerobios metronidazol piperacilina tazobactam carbapenemico",
  },
  {
    id: "atypicals",
    dex: "AT001",
    group: "atypical",
    name: "Mycoplasma / Chlamydia / Legionella",
    short: "Atípicos",
    icon: "🟡",
    type: "intracelulares/sin pared",
    tags: ["No beta", "NAC"],
    syndromes: "Neumonía atípica, brotes, exposición a aerosoles/agua en Legionella.",
    cover: "Macrólidos, doxiciclina o fluoroquinolonas respiratorias según síndrome y gravedad.",
    gap: "Los beta-lactámicos no cubren atípicos.",
    trap: "Beta-lactámico perfecto + Legionella = fallo si no añades cobertura intracelular.",
    search: "mycoplasma chlamydia legionella atipicos macrolidos doxiciclina beta lactamicos",
  },
];

export const ORGANISMS = Object.freeze(
  organismData.map((item) => Object.freeze({ ...item, sourceIds: item.sourceIds ?? LOCAL_SOURCE })),
);

const antibioticData = [
  { id: "pen-g", dex: "B001", group: "blue", name: "Penicilina G", family: "Penicilina natural", icon: "💊", type: "Gram + estrecho", covers: ["S. pyogenes", "Treponema", "Listeria", "E. faecalis sensible"], misses: ["SASM productor de penicilinasa", "Enterobacterales", "Pseudomonas"], trap: "Enterococcus: actividad inhibitoria; si buscas bactericidia, precisa estrategia sinérgica.", search: "penicilina g treponema listeria enterococcus streptococcus" },
  { id: "amp-amox", dex: "B002", group: "green", name: "Ampicilina / amoxicilina", family: "Aminopenicilina", icon: "💊", type: "Listeria/Enterococcus", covers: ["Streptococcus", "E. faecalis sensible", "Listeria"], misses: ["Pseudomonas", "SARM", "S. aureus habitual", "β-lactamasas sin inhibidor"], trap: "En meningitis de anciano/inmunodeprimido, es el hueco que añade cobertura anti-Listeria.", search: "ampicilina amoxicilina enterococcus listeria meningitis" },
  { id: "amoxclav", dex: "B003", group: "green", name: "Amoxicilina-clavulánico", family: "Aminopenicilina + inhibidor", icon: "💊", type: "Polimicrobiano comunitario", covers: ["ORL/respiratorio con β-lactamasa", "Mordeduras", "Odontógeno", "Anaerobios comunitarios", "E. faecalis sensible"], misses: ["Pseudomonas", "SARM", "BLEE grave", "AmpC relevante", "pauta de meningitis por Listeria"], trap: "Si hay actividad frente a Listeria, la aporta amoxicilina; no es pauta de meningitis.", search: "amoxicilina clavulanico amoxclav anaerobios mordeduras enterococcus listeria no meningitis" },
  { id: "cloxa-cefa", dex: "B004", group: "blue", name: "Cloxacilina / cefazolina", family: "Anti-SASM", icon: "💊", type: "SASM dirigido", covers: ["SASM", "Streptococcus"], misses: ["SARM", "Enterococcus", "Listeria", "Pseudomonas", "Anaerobios profundos"], trap: "Para SASM dirigido, son preferentes frente a ceftriaxona o pip-tazo.", search: "cloxacilina cefazolina sasm mssa staphylococcus" },
  { id: "cefuroxime", dex: "C002", group: "blue", name: "Cefuroxima", family: "Cefalosporina 2ª", icon: "💊", type: "Respiratorio/ITU seleccionado", covers: ["Streptococcus", "SASM variable", "H. influenzae/Moraxella", "algunos GN comunitarios"], misses: ["Pseudomonas", "Enterococcus", "Listeria", "BLEE/CRE", "Anaerobios profundos"], trap: "No la conviertas en antipseudomónico ni en tratamiento de foco profundo anaerobio.", search: "cefuroxima segunda respiratorio moraxella haemophilus" },
  { id: "ceftriaxone", dex: "C003", group: "blue", name: "Ceftriaxona / cefotaxima", family: "Cefalosporina 3ª no pseudomónica", icon: "💊", type: "Enterobacterales comunitarias", covers: ["E. coli/Klebsiella/Proteus no BLEE", "Neumococo", "Meningococo", "Gonococo"], misses: ["Pseudomonas", "Enterococcus", "Listeria", "SARM", "Anaerobios"], trap: "La gran trampa de guardia: cómoda, pero deja huecos críticos.", search: "ceftriaxona cefotaxima enterobacterales meningitis pseudomonas enterococcus listeria anaerobios" },
  { id: "ceftazidime", dex: "C004", group: "green", name: "Ceftazidima", family: "Cefalosporina 3ª pseudomónica", icon: "💊", type: "Pseudomonas", covers: ["Pseudomonas si sensible", "BGN aerobios"], misses: ["Anaerobios", "Enterococcus", "Listeria", "SARM", "Gram+ potente"], trap: "No es “ceftriaxona plus”: pierde mucho Gram+ y no cubre anaerobios.", search: "ceftazidima pseudomonas anaerobios grampositivos" },
  { id: "cefepime", dex: "C005", group: "amber", name: "Cefepime", family: "Cefalosporina 4ª", icon: "💊", type: "AmpC/Pseudomonas", covers: ["AmpC si CMI favorable", "Pseudomonas si sensible", "Enterobacterales no BLEE"], misses: ["BLEE dirigida", "Anaerobios", "Enterococcus", "Listeria", "SARM"], trap: "Ajuste renal obligatorio: neurotoxicidad si se olvida.", search: "cefepime ampc pseudomonas blee neurotoxicidad" },
  { id: "piptazo", dex: "P001", group: "green", name: "Piperacilina-tazobactam", family: "Penicilina antipseudomónica + inhibidor", icon: "💊", type: "Amplio con anaerobios", covers: ["Pseudomonas si sensible", "Anaerobios", "Enterobacterales no BLEE", "SASM", "E. faecalis sensible"], misses: ["SARM", "E. faecium resistente", "Carbapenemasas", "BLEE grave fiable"], trap: "En BLEE extraurinaria grave, no usar como dirigida aunque parezca sensible.", search: "piperacilina tazobactam pip tazo pseudomonas anaerobios blee" },
  { id: "ertapenem", dex: "K001", group: "blue", name: "Ertapenem", family: "Carbapenémico grupo 1", icon: "💊", type: "BLEE estable", covers: ["Enterobacterales BLEE", "Anaerobios", "muchos Gram+ comunitarios"], misses: ["Acinetobacter", "Pseudomonas", "Enterococcus"], trap: "APE: Acinetobacter, Pseudomonas, Enterococcus quedan fuera.", search: "ertapenem blee ape acinetobacter pseudomonas enterococcus" },
  { id: "mero-imi", dex: "K002", group: "red", name: "Meropenem / imipenem", family: "Carbapenémico antipseudomónico", icon: "💊", type: "UCI/MDR", covers: ["BLEE", "AmpC", "Anaerobios", "Pseudomonas si sensible"], misses: ["SARM", "Stenotrophomonas", "Atípicos", "Enterococcus resistente"], trap: "No gastar carbapenémico si el problema es colonización o cistitis baja con opción oral activa.", search: "meropenem imipenem carbapenemico blee ampc pseudomonas anaerobios" },
  { id: "aztreonam", dex: "M001", group: "amber", name: "Aztreonam", family: "Monobactámico", icon: "💊", type: "Solo GN aerobios", covers: ["Enterobacterales si sensible", "Pseudomonas si sensible"], misses: ["Gram positivos", "Anaerobios"], trap: "Comparte cadena lateral con ceftazidima: cuidado si alergia confirmada a ceftazidima.", search: "aztreonam monobactam alergia ceftazidima pseudomonas anaerobios" },
  { id: "anti-mrsa-ceph", dex: "C006", group: "blue", name: "Ceftarolina (ceftobiprol no intercambiable)", family: "Cefalosporina anti-SARM", icon: "💊", type: "Anti-SARM beta-lactámico", covers: ["SARM", "SASM", "Streptococcus", "neumococo resistente"], misses: ["Pseudomonas en ceftarolina", "BLEE/CRE/AmpC", "Enterococcus fiable"], trap: "Anti-SARM dirigido, no comodín MDR. No extrapolar ceftarolina y ceftobiprol como equivalentes.", search: "ceftarolina ceftobiprol no intercambiable sarm mrsa neumococo blee cre ampc" },
  { id: "caz-avi", dex: "N001", group: "red", name: "Ceftazidima-avibactam", family: "Nuevo BL/BLI", icon: "🧬", type: "KPC/OXA-48-like", covers: ["KPC", "OXA-48-like", "algunas Pseudomonas DTR si sensible"], misses: ["MBL en monoterapia", "Gram+ y anaerobios relevantes"], trap: "MBL: combinar con aztreonam o elegir otra estrategia según disponibilidad/AST.", search: "ceftazidima avibactam caz avi kpc oxa48 mbl aztreonam", sourceIds: AMR_SOURCES },
  { id: "ceftolo-tazo", dex: "N002", group: "green", name: "Ceftolozano-tazobactam", family: "Nuevo BL/BLI", icon: "🧬", type: "Pseudomonas DTR", covers: ["Pseudomonas MDR/DTR si sensible", "algunas BLEE pero no como referencia"], misses: ["KPC", "OXA-48", "MBL", "Anaerobios sin metronidazol"], trap: "Especialista en Pseudomonas; no lo uses como carbapenemasa-killer.", search: "ceftolozano tazobactam pseudomonas dtr blee kpc", sourceIds: AMR_SOURCES },
  { id: "mvb-imi-rel", dex: "N003", group: "red", name: "Meropenem-vaborbactam / imipenem-relebactam", family: "Nuevo BL/BLI", icon: "🧬", type: "KPC", covers: ["KPC", "algunas Pseudomonas DTR si sensible en IMI-REL"], misses: ["MBL", "OXA-48-like en MVB/IMI-REL"], trap: "Si es OXA-48 o MBL, cambiar de mapa.", search: "meropenem vaborbactam imipenem relebactam kpc oxa48 mbl", sourceIds: AMR_SOURCES },
  { id: "cefiderocol", dex: "N004", group: "red", name: "Cefiderocol", family: "Cefalosporina sideróforo", icon: "🧬", type: "MDR/XDR", covers: ["MBL como opción", "algunos no fermentadores MDR", "CRE según AST"], misses: ["Gram+", "Anaerobios"], trap: "Último recurso: siempre con AST, foco claro y PROA/Infecciosas.", search: "cefiderocol sideroforo mbl crab pseudomonas dtr", sourceIds: AMR_SOURCES },
  { id: "vanco", dex: "O001", group: "amber", name: "Vancomicina", family: "Glucopéptido", icon: "🛡️", type: "Gram+ resistentes", covers: ["SARM", "E. faecium sensible", "Gram+ resistentes"], misses: ["Gram negativos", "CDI luminal por vía IV"], trap: "IV no trata luz colónica; para CDI, vía oral/fidaxomicina según caso.", search: "vancomicina sarm c difficile oral iv niveles" },
  { id: "dapto", dex: "O002", group: "blue", name: "Daptomicina", family: "Lipopeptido", icon: "🛡️", type: "SARM/ERV no pulmonar", covers: ["Bacteriemia por Gram+", "endocarditis derecha", "osteoarticular", "IPPB"], misses: ["Neumonía"], trap: "Surfactante pulmonar la inactiva. CK y estatinas.", search: "daptomicina neumonia surfactante ck sarm erv" },
  { id: "tmp-smx", dex: "O003", group: "amber", name: "Cotrimoxazol", family: "TMP-SMX", icon: "🧪", type: "Oral útil / Steno", covers: ["Stenotrophomonas si sensible", "algunas ITU", "Pneumocystis"], misses: ["Pseudomonas", "anaerobios"], trap: "Vigilar potasio, función renal y hemograma.", search: "cotrimoxazol tmp smx stenotrophomonas potasio hemograma" },
  { id: "metro", dex: "O004", group: "blue", name: "Metronidazol", family: "Nitroimidazol", icon: "🧪", type: "Anaerobios", covers: ["Anaerobios", "protozoos seleccionados"], misses: ["Aerobios", "Gram+ y GN no anaerobios"], trap: "Ceftriaxona + metronidazol es una lógica; metronidazol solo rara vez lo es en foco polimicrobiano.", search: "metronidazol anaerobios abdomen ceftriaxona" },
];

export const ANTIBIOTICS = Object.freeze(
  antibioticData.map((item) => Object.freeze({ ...item, sourceIds: item.sourceIds ?? LOCAL_SOURCE })),
);

const mechanismData = [
  { id: "blee", name: "BLEE", icon: "🧬", group: "green", question: "¿Cistitis, pielonefritis/cUTI o infección invasiva?", use: "Cistitis baja: opción urinaria activa. Pielonefritis/cUTI: TMP-SMX/quinolona si sensible o carbapenémico. Extraurinaria grave: carbapenémico.", avoid: "Pip-tazo o cefepime como dirigidos en BLEE extraurinaria grave; nitrofurantoína/fosfomicina si pielonefritis.", micro: "AST completo, foco y posibilidad real de paso oral.", search: "blee esbl carbapenemico cistitis pielonefritis cuti cefepime piperacilina" },
  { id: "ampc", name: "AmpC inducible", icon: "🧬", group: "amber", question: "¿E. cloacae complex, K. aerogenes o C. freundii?", use: "Cefepime si sensible y CMI favorable. Carbapenémico si grave, foco profundo, CMI problemática o sospecha de BLEE coproducida.", avoid: "Ceftriaxona/cefotaxima/ceftazidima en infección invasiva por especies de riesgo.", micro: "Identificar especie y CMI de cefepime; valorar BLEE coproducida.", search: "ampc enterobacter cloacae complex klebsiella aerogenes citrobacter freundii cefepime ceftriaxona" },
  { id: "kpc", name: "CRE-KPC", icon: "🧬", group: "red", question: "¿Carbapenemasa KPC confirmada?", use: "Meropenem-vaborbactam, ceftazidima-avibactam o imipenem-relebactam si sensible.", avoid: "Combinaciones antiguas con aminoglucósido/polimixina si ya hay beta-lactámico activo.", micro: "Tipado de carbapenemasa + AST de nuevos BL/BLI.", search: "kpc cre meropenem vaborbactam ceftazidima avibactam imipenem relebactam" },
  { id: "oxa48", name: "CRE OXA-48-like", icon: "🧬", group: "red", question: "¿OXA-48-like?", use: "Ceftazidima-avibactam como referencia si sensible. Cefiderocol como alternativa según caso.", avoid: "Meropenem-vaborbactam o imipenem-relebactam como si fueran KPC.", micro: "Tipado de carbapenemasa; confirmar actividad de CAZ-AVI.", search: "oxa48 oxa 48 ceftazidima avibactam cefiderocol" },
  { id: "mbl", name: "MBL", icon: "🧬", group: "red", question: "¿NDM/VIM/IMP?", use: "Ceftazidima-avibactam + aztreonam o cefiderocol. Aztreonam-avibactam/cefepime-zidebactam según disponibilidad.", avoid: "CAZ-AVI en monoterapia. Vaborbactam/relebactam no inhiben MBL.", micro: "Probar combinación CAZ-AVI + aztreonam si el laboratorio puede.", search: "mbl ndm vim imp aztreonam avibactam cefiderocol" },
  { id: "dtr-pa", germId: "dtr", name: "Pseudomonas DTR", icon: "🧬", group: "green", question: "¿Conserva algún beta-lactámico clásico?", use: "Si conserva BL clásico no carbapenémico, usarlo a dosis altas/perfusión extendida. Si DTR: ceftolo-tazo, CAZ-AVI, IMI-REL o cefiderocol según AST.", avoid: "Combinación de rutina si ya hay beta-lactámico activo confirmado.", micro: "AST para nuevos BL/BLI y cefiderocol.", search: "pseudomonas dtr ceftolozano tazobactam cefiderocol" },
  { id: "crab", name: "CRAB", icon: "🧬", group: "red", question: "¿Infección real o colonización?", use: "Sulbactam-durlobactam + meropenem/imipenem si disponible. Si no, ampicilina-sulbactam alta dosis + otro agente.", avoid: "Meropenem/imipenem solos. Tratar colonización respiratoria sin síndrome.", micro: "Confirmar sensibilidad y discutir combinación con PROA.", search: "crab acinetobacter sulbactam durlobactam colistina cefiderocol" },
  { id: "steno", name: "Stenotrophomonas", icon: "🧬", group: "amber", question: "¿Colonización o infección real moderada-grave?", use: "Infección real + AST + PROA. Dos agentes entre cefiderocol, minociclina, TMP-SMX o levofloxacino; alternativa CAZ-AVI + aztreonam.", avoid: "Ceftazidima y carbapenémicos. Tratar hallazgo casual en vía aérea.", micro: "Solicitar sensibilidad a TMP-SMX, levofloxacino, minociclina y cefiderocol; discutir si hay que combinar.", search: "stenotrophomonas infeccion real ast proa tmp smx minociclina levofloxacino cefiderocol" },
];

export const MECHANISMS = Object.freeze(
  mechanismData.map((item) => Object.freeze({ ...item, sourceIds: ["idsa-amr-2024"] })),
);

const caseData = [
  { id: "listeria-meningitis", title: "Anciano con meningitis", setup: "Ceftriaxona cubre neumococo y meningococo, pero el paciente tiene riesgo de Listeria.", answer: "Añade ampicilina IV o amoxicilina IV según protocolo. Ceftriaxona sola deja hueco LAME: Listeria." },
  { id: "ampc-ceftriaxone", title: "Enterobacter cloacae bacteriémico “S” a ceftriaxona", setup: "El informe inicial puede parecer cómodo, pero es una especie de riesgo AmpC.", answer: "Evita ceftriaxona en infección invasiva. Cefepime si CMI favorable o carbapenémico si gravedad/CMI/BLEE.", sourceIds: AMR_SOURCES },
  { id: "ertapenem-pseudomonas", title: "Ertapenem para neumonía nosocomial con riesgo de Pseudomonas", setup: "Ertapenem cubre BLEE y anaerobios, pero tiene hueco APE.", answer: "Error: no cubre Pseudomonas. Usa antipseudomónico real si el riesgo es clínicamente relevante." },
  { id: "steno-colonization", title: "Stenotrophomonas en esputo de EPOC estable", setup: "No fermentador en vía aérea crónica sin fiebre, sin infiltrado nuevo, sin deterioro claro.", answer: "Probable colonización. No escalar por cultivo aislado; tratar solo si síndrome infeccioso real.", sourceIds: AMR_SOURCES },
  { id: "blee-branches", title: "BLEE no es una sola rama", setup: "El mismo antibiograma no significa lo mismo en cistitis baja, pielonefritis/cUTI o bacteriemia.", answer: "Cistitis baja: opción urinaria activa. Pielo/cUTI: TMP-SMX/quinolona si sensible o carbapenémico. Bacteriemia/foco extraurinario: carbapenémico; si crítico, meropenem/imipenem.", sourceIds: AMR_SOURCES },
  { id: "gonococcus-pharynx", title: "Gonococo faríngeo tratado con cefixima", setup: "Cefixima puede aparecer como alternativa oral, pero faringe es un sitio de erradicación difícil.", answer: "Ceftriaxona si es posible. Si hubo cefixima o sospecha de fallo: test de curación 7-14 días; cultivo/AST y experto si persiste.", sourceIds: ["cdc-gonorrhea-2021"] },
  { id: "daptomycin-pneumonia", title: "Daptomicina para neumonía por SARM", setup: "Daptomicina es potente anti-SARM, pero no en pulmón.", answer: "Error de foco: se inactiva por surfactante. Considera linezolid/vancomicina según contexto y protocolo." },
];

export const CASES = Object.freeze(
  caseData.map((item) => Object.freeze({ ...item, sourceIds: item.sourceIds ?? LOCAL_SOURCE })),
);

export const DEEP_SECTIONS = Object.freeze([
  { title: "Cinco filtros antes de prescribir", body: ["Foco: respiratorio, urinario, abdominal, piel, catéter, SNC o foco incierto.", "Patógeno que no puedes fallar: Pseudomonas, Enterococcus/Listeria, SASM/SARM, anaerobios, BLEE/AmpC o no fermentadores.", "Mecanismo probable: BLEE, AmpC, CRE/KPC/OXA-48/MBL, Pseudomonas DTR, CRAB o Stenotrophomonas.", "Exposición real: sepsis, shock, neutropenia, foco profundo o CMI alta cambian la pauta.", "Salida escrita: cultivos, control de foco, desescalada, paso oral y duración."] },
  { title: "Reglas LAME y APE", body: ["LAME resume huecos comunes de cefalosporinas: Listeria, Atípicos, MRSA/SARM y Enterococo. Ceftarolina es excepción anti-SARM, no solución universal; ceftobiprol no se debe intercambiar sin ficha/protocolo.", "APE resume los huecos de ertapenem: Acinetobacter, Pseudomonas y Enterococcus. Muy útil en BLEE estable si esos tres no importan."] },
  { title: "Cómo pensar un gramnegativo resistente", body: ["No trates un antibiograma sin síndrome clínico compatible.", "Separa cistitis baja de pielonefritis, bacteriemia, neumonía, abdomen o shock.", "CRE exige tipado de carbapenemasa: KPC, OXA-48-like, MBL o no carbapenemasa llevan a opciones distintas.", "CRAB y Stenotrophomonas se colonizan con facilidad: confirmar infección real antes de combinar."] },
  { title: "Otros antimicrobianos: foco-veto", body: ["Aminoglucósidos y vancomicina/teicoplanina exigen plan de niveles o vigilancia cuando el curso no es puntual.", "Daptomicina no trata neumonía por inactivación por surfactante.", "Tigeciclina no debe ser columna vertebral de bacteriemia por niveles séricos bajos.", "Fosfomicina IV aporta carga sódica relevante.", "Colistina es rescate, tóxica y no debería usarse como monoterapia de reflejo."] },
]);

export const COMBINATION_GAPS = Object.freeze([
  "Abdomen comunitario estable: ceftriaxona + metronidazol puede encajar si no necesitas Enterococcus, Pseudomonas ni cobertura MDR.",
  "Abdomen grave, nosocomial o con exposición sanitaria: no convertir ceftriaxona + metronidazol en regla; valorar pip-tazo/carbapenémico/nuevos BL-BLI según foco, AST y PROA.",
  "Cefepime/ceftazidima + intraabdominal: no cubren anaerobios ni Enterococcus; añadir lo que falte si el foco lo exige.",
  "Aztreonam en alergia grave: añadir cobertura grampositiva y anaerobia si el foco lo exige; evitarlo si alergia confirmada a ceftazidima.",
  "Pseudomonas MDR, CRE, MBL, CRAB o Stenotrophomonas: manejo dirigido por AST y consulta.",
]);
