export const SOURCES = Object.freeze({
  "classification-image": Object.freeze({
    id: "classification-image",
    title: "Tabla de clasificación bacteriana aportada por el usuario",
    version: "Imagen original · edición no identificada",
    registeredAt: "2026-09-20",
    scope: "Origen del esquema. Se conserva sin cambios para cotejarlo; las notas de la sección explican las correcciones y los datos no corroborados.",
    url: "assets/clasificacion-bacteriana-original.png",
  }),
  "uk-smi-id1": Object.freeze({
    id: "uk-smi-id1",
    title: "UK SMI ID 1 · Identificación de bacterias de importancia médica",
    version: "4 · 06-08-2025 · algoritmos de morfología",
    registeredAt: "2026-09-20",
    scope: "Gram, morfología y crecimiento; orientación de identificación, con variabilidad y necesidad de confirmación microbiológica.",
    url: "https://www.rcpath.org/asset/7BCE1B56-E62F-4FE2-AA6EAB8930779A24/",
  }),
  "uk-smi-id4": Object.freeze({
    id: "uk-smi-id4",
    title: "UK SMI ID 4 · Streptococcus, Enterococcus y microorganismos similares",
    version: "4 · 22-09-2021",
    registeredAt: "2026-09-20",
    scope: "Hemólisis, Lancefield, optoquina, bilis-esculina y PYR. Matices de S. dysgalactiae, grupo S. anginosus y enterococos.",
    url: "https://www.rcpath.org/asset/CE35B1B6-9D79-4125-A0F64BA28E9A3584/",
  }),
  "uk-smi-id7": Object.freeze({
    id: "uk-smi-id7",
    title: "UK SMI ID 7 · Staphylococcus, Micrococcus y Rothia",
    version: "4 · 26-05-2020",
    registeredAt: "2026-09-20",
    scope: "Coagulasa, novobiocina y limitaciones de las pruebas; S. lugdunensis puede tener aglutinación positiva con coagulasa en tubo negativa.",
    url: "https://www.rcpath.org/asset/DB5F13CB-53CA-4E9E-A0937B78B610D0AC/",
  }),
  "uk-smi-id16": Object.freeze({
    id: "uk-smi-id16",
    title: "UK SMI ID 16 · Identificación de Enterobacteriaceae",
    version: "4 · 13-04-2015 · nomenclatura de la fuente",
    registeredAt: "2026-09-20",
    scope: "Lactosa y rasgos bioquímicos variables de enterobacterias. No respalda el porcentaje 10–15 % de la imagen como estimación actual.",
    url: "https://www.rcpath.org/asset/28C29E82-88C1-4DD3-8F73BA01FA251D49/",
  }),
  "uk-smi-id17": Object.freeze({
    id: "uk-smi-id17",
    title: "UK SMI ID 17 · Pseudomonas y otros no fermentadores de glucosa",
    version: "4.1 · 31-07-2025 · tabla 2",
    registeredAt: "2026-09-20",
    scope: "Oxidasa positiva en P. aeruginosa y negativa en Acinetobacter y S. maltophilia; excepciones dentro del género Pseudomonas.",
    url: "https://www.rcpath.org/asset/BFD560D2-EB3A-4260-BF1F63FEEE21325A/",
  }),
  "eucast-expected-phenotypes": Object.freeze({
    id: "eucast-expected-phenotypes",
    title: "EUCAST · Fenotipos de resistencia esperados",
    version: "1.2 · enero de 2023 · tabla 4",
    registeredAt: "2026-09-20",
    scope: "Resistencia esperada a vancomicina en E. gallinarum, E. casseliflavus, Leuconostoc y Pediococcus. No atribuye sensibilidad universal a E. faecalis o E. faecium.",
    url: "https://www.eucast.org/fileadmin/eucast/pdf/expert_rules/Expected_Resistant_Phenotypes_v1.2_20230113.pdf",
  }),
  "uk-smi-id26": Object.freeze({
    id: "uk-smi-id26",
    title: "UK SMI ID 26 · Identificación de Helicobacter",
    version: "3.1 · 18-09-2025 · revisión científica de 2015",
    registeredAt: "2026-09-20",
    scope: "Morfología y crecimiento microaerófilo, apartado 4.2. La actualización de 2025 es administrativa; no se usa para recomendaciones terapéuticas.",
    url: "https://www.rcpath.org/asset/03A7F1ED-EF84-497C-AF44A9745EA5A051/",
  }),
  "asm-achromobacter": Object.freeze({
    id: "asm-achromobacter",
    title: "ASM · Achromobacter Infections and Treatment Options",
    version: "Antimicrobial Agents and Chemotherapy · 2020",
    registeredAt: "2026-09-20",
    scope: "Únicamente características de identificación: bacilo gramnegativo aerobio, no fermentador y oxidasa positivo. No se importan opciones de tratamiento.",
    url: "https://journals.asm.org/doi/10.1128/aac.01025-20",
  }),
  "idsa-ampc-identification": Object.freeze({
    id: "idsa-ampc-identification",
    title: "IDSA 2026 · Especies y riesgo de AmpC inducible",
    version: "Apartado 2.1 · revisión dirigida",
    registeredAt: "2026-09-20",
    scope: "Diferencias por especie, inclusión de H. alvei con evidencia clínica limitada y corrección de la generalización de AmpC a Proteus.",
    url: "https://www.idsociety.org/practice-guideline/amr-guidance/",
  }),
  "manual-12-microbiology": Object.freeze({
    id: "manual-12-microbiology",
    title: "Manual de Diagnóstico y Terapéutica Médica · Hospital 12 de Octubre",
    version: "2022 · p. 970, tabla 7, nota 1",
    registeredAt: "2026-09-20",
    scope: "S. lugdunensis: estafilococo coagulasa negativo de alta virulencia. Comprobado en la página 986 del PDF local. No se han trasladado dosis ni pautas de esa tabla.",
    url: null,
  }),
  "local-proa-fjd": Object.freeze({
    id: "local-proa-fjd",
    title: "Material local PROA FJD y vault MIR",
    version: "Documentos locales revisados para esta edición",
    registeredAt: "2026-08-10",
    scope:
      "PROA - Betalactámicos y Cefalosporinas; Sepsis - Antiinfecciosos y Soporte Vital; Meningitis y Encefalitis.",
    url: null,
  }),
  "idsa-amr-2024": Object.freeze({
    id: "idsa-amr-2024",
    title:
      "IDSA 2024 Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections",
    version: "4.0 (2024)",
    registeredAt: "2026-08-10",
    scope: "BLEE, AmpC, CRE, Pseudomonas DTR, CRAB y Stenotrophomonas.",
    url: "https://www.idsociety.org/globalassets/idsa/practice-guidelines/amr-guidance/4.0/amr-guidance-4.0.pdf",
  }),
  "cdc-gonorrhea-2021": Object.freeze({
    id: "cdc-gonorrhea-2021",
    title:
      "CDC STI Treatment Guidelines: Gonococcal Infections Among Adolescents and Adults",
    version: "2021",
    registeredAt: "2026-08-10",
    scope: "Gonococo, infección faríngea, test de curación y sospecha de fallo.",
    url: "https://www.cdc.gov/std/treatment-guidelines/gonorrhea-adults.htm",
  }),
  "idsa-amr-2026": Object.freeze({
    id: "idsa-amr-2026",
    title: "IDSA 2026 Guidance on Antimicrobial Resistant Gram-Negative Infections",
    version: "30 de julio de 2026 · revisión parcial",
    registeredAt: "2026-09-20",
    scope: "BLEE (1.1–1.3), rutas de AmpC (2.3–2.7), selección dirigida en Pseudomonas (4.1), NDM (3.5) y Stenotrophomonas invasiva (6.1–6.6). Orientación de EE. UU.; adaptar a disponibilidad, criterios de sensibilidad y PROA local. Revisión dirigida, no actualización íntegra del atlas.",
    url: "https://www.idsociety.org/practice-guideline/amr-guidance/",
  }),
  "idsa-sab-2026": Object.freeze({
    id: "idsa-sab-2026",
    title: "IDSA/ESCMID · Bacteriemia por Staphylococcus aureus",
    version: "Consenso de 9 de septiembre de 2026 · parte 1",
    registeredAt: "2026-09-20",
    scope: "Evaluación y seguimiento en adultos: hemocultivos de control, ecocardiografía, focos secundarios y duración individualizada. Esta parte no establece la selección del antibiótico.",
    url: "https://www.idsociety.org/practice-guideline/staphylococcus-aureus-bacteremia/",
  }),
  "esc-endocarditis-2023": Object.freeze({
    id: "esc-endocarditis-2023",
    title: "ESC · Guía de endocarditis",
    version: "2023 · apartados 7.6–7.8",
    registeredAt: "2026-09-20",
    scope: "Estafilococos y Enterococcus: diferencias por especie, sensibilidad y válvula nativa o protésica. Contrastado con el PDF original local, páginas 3979–3982. No se reproducen dosis ni duraciones como pautas automáticas.",
    url: "https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/endocarditis/",
  }),
  "idsa-ssti-2014": Object.freeze({
    id: "idsa-ssti-2014",
    title: "IDSA · Infecciones de piel y partes blandas",
    version: "2014 · abscesos, celulitis e infección necrosante",
    registeredAt: "2026-09-20",
    scope: "Drenaje, cultivo, cobertura de SASM/SARM y estreptococos, y valoración quirúrgica urgente si se sospecha necrosis. Adaptar a resistencias y protocolo local.",
    url: "https://www.idsociety.org/practice-guideline/skin-and-soft-tissue-infections/",
  }),
  "idsa-hap-vap-2016": Object.freeze({
    id: "idsa-hap-vap-2016",
    title: "ATS/IDSA · Neumonía hospitalaria y asociada a ventilación",
    version: "2016 · tratamiento dirigido de SARM y Pseudomonas",
    registeredAt: "2026-09-20",
    scope: "Vancomicina/linezolid en SARM; tratamiento según sensibilidad en Pseudomonas y reconsideración de la combinación según shock y evolución. El ámbito de la guía es la neumonía hospitalaria o asociada a ventilación.",
    url: "https://www.idsociety.org/practice-guideline/hap_vap/",
  }),
  "aemps-linezolid": Object.freeze({
    id: "aemps-linezolid",
    title: "AEMPS CIMA · Linezolid Glenmark 600 mg",
    version: "Ficha técnica · apartados 4.1 y 4.4",
    registeredAt: "2026-09-20",
    scope: "Indicaciones respiratorias por grampositivos sensibles y precauciones hematológicas e interacciones. No extrapolar cobertura a gramnegativos ni asumir que basta ante bacteriemia concomitante.",
    url: "https://cima.aemps.es/cima/dochtml/ft/81569/FT_81569.html",
  }),
  "aemps-meropenem": Object.freeze({
    id: "aemps-meropenem",
    title: "AEMPS CIMA · Meronem I.V. 1 g",
    version: "Ficha técnica consultada · apartados 4.1 y 5.1",
    registeredAt: "2026-09-19",
    scope: "Meropenem: actividad frente a Listeria y matiz de sensibilidad natural intermedia de E. faecalis. No equivale a elección terapéutica por foco.",
    url: "https://cima.aemps.es/cima/dochtml/ft/60640/FT_60640.html",
  }),
  "aemps-imipenem": Object.freeze({
    id: "aemps-imipenem",
    title: "AEMPS CIMA · Imipenem/Cilastatina Kabi 500 mg/500 mg",
    version: "Ficha técnica consultada · apartados 4.4 y 5.1",
    registeredAt: "2026-09-19",
    scope: "E. faecalis frecuentemente sensible; E. faecium resistente. Imipenem/cilastatina no se recomienda para meningitis.",
    url: "https://cima.aemps.es/cima/dochtml/ft/71285/FichaTecnica_71285.html",
  }),
  "dailymed-imipenem": Object.freeze({
    id: "dailymed-imipenem",
    title: "DailyMed · PRIMAXIN IV (imipenem/cilastatina)",
    version: "Ficha estadounidense · apartado 12.4",
    registeredAt: "2026-09-19",
    scope: "Actividad in vitro frente a Listeria; eficacia clínica no establecida en ensayos adecuados. No usar como recomendación de tratamiento ni extrapolar indicaciones de EE. UU.",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f41d8abd-7792-4918-1b93-bd83ea01955e",
  }),
  "aemps-ciprofloxacin": Object.freeze({
    id: "aemps-ciprofloxacin",
    title: "AEMPS CIMA · Ciprofloxacino Ratio 250 mg",
    version: "Ficha técnica consultada · apartados 4.1–4.5 y 5.1",
    registeredAt: "2026-09-19",
    scope: "Espectro, eficacia insuficiente frente a estreptococos, resistencias adquiridas, foco urinario, función renal e interacción con tizanidina. Sin extrapolar dosis.",
    url: "https://cima.aemps.es/cima/dochtml/ft/67095/FT_67095.html",
  }),
  "aemps-levofloxacin": Object.freeze({
    id: "aemps-levofloxacin",
    title: "AEMPS CIMA · Levofloxacino cinfa 500 mg",
    version: "Ficha técnica consultada · apartados 4.1–4.5 y 5.1",
    registeredAt: "2026-09-19",
    scope: "Espectro respiratorio y urinario, actividad condicionada por AST, restricciones en NAC y necesidad de ajuste renal. Sin incorporar pautas posológicas.",
    url: "https://cima.aemps.es/cima/dochtml/ft/75614/FT_75614.html",
  }),
  "aemps-moxifloxacin": Object.freeze({
    id: "aemps-moxifloxacin",
    title: "AEMPS CIMA · Moxifloxacino Sandoz 400 mg",
    version: "Ficha técnica oral consultada · apartados 4.1–4.5 y 5.1–5.2",
    registeredAt: "2026-09-19",
    scope: "Espectro respiratorio, ausencia de actividad anti-Pseudomonas, anaerobios variables, QT y ausencia de indicación urinaria. No extrapolar indicaciones entre presentaciones oral e IV.",
    url: "https://cima.aemps.es/cima/dochtml/ft/74573/FichaTecnica_74573.html",
  }),
  "aemps-fluoroquinolonas": Object.freeze({
    id: "aemps-fluoroquinolonas",
    title: "AEMPS · Fluoroquinolonas: restricciones de uso",
    version: "Nota de seguridad MUH (FV), 07/2023 · 23-10-2023",
    registeredAt: "2026-09-19",
    scope: "Uso restringido, reacción grave previa, daños tendinosos/neurológicos y factores de riesgo. Beneficio-riesgo individual; no selección automática por espectro.",
    url: "https://www.aemps.gob.es/informa/fluoroquinolonas-de-administracion-sistemica-o-inhalada-recordatorio-sobre-las-restricciones-de-uso/",
  }),
  "eucast-2026-quinolones": Object.freeze({
    id: "eucast-2026-quinolones",
    title: "EUCAST · Clinical Breakpoint Tables",
    version: "16.1 · 24-06-2026",
    registeredAt: "2026-09-19",
    scope: "Quinolonas: límites por foco en Enterococcus (p. 41), estreptococos y evidencia insuficiente para moxifloxacino en meningitis por Listeria (p. 90). El atlas no reproduce puntos de corte ni usa sus símbolos como categorías S/I/R.",
    url: "https://www.eucast.org/fileadmin/eucast/pdf/breakpoints/v_16.1_Breakpoint_Tables.pdf",
  }),
});

export function getSources(sourceIds) {
  return sourceIds.map((sourceId) => SOURCES[sourceId]).filter(Boolean);
}
